# a very minimal declarative config file
_format_version: "3.0"
_transform: true
services:
  - name: ping_service
    tags:
      - tag
    read_timeout: 60000
    retries: 5
    connect_timeout: 60000
    write_timeout: 60000
    port: 80
    url: http://ping:80/
    routes:
      - name: albums_route
        paths:
          - /albums
        strip_path: true
plugins:
  - name: jwt
    enabled: true
    service:
      id: 914e5743-2f11-5a24-9643-f2e92ac2ba51
    route:
      id: 99405430-4091-529b-b749-f0d88616da8f
    protocols:
      - grpc
      - grpcs
      - http
      - https
    config:
      cookie_names: []
      header_names:
        - authorization
      key_claim_name: iss
      maximum_expiration: 0
      run_on_preflight: true
      secret_is_base64: false
      uri_param_names:
        - jwt